const SEARCH_CRITERIA_ID_DOB = 'option1'
const SEARCH_CRITERIA_ID_NAME = 'option2'
const SEARCH_CRITERIA_NAME_DOB = 'option3'

export {
  SEARCH_CRITERIA_ID_DOB,
  SEARCH_CRITERIA_ID_NAME,
  SEARCH_CRITERIA_NAME_DOB,
}
